version: '3.7'

# Basic function options
x-victim: &victim
  labels:
    class: 'victim'
    cluster: 'pentest_lab'
x-monitoring: &monitoring
  labels:
    class: 'monitoring'
    cluster: 'pentest_lab'
x-red_team: &red_team
  labels:
    class: 'red_team'
    cluster: 'pentest_lab'
x-blue_team: &blue_team
  labels:
    class: 'blue_team'
    cluster: 'pentest_lab'
x-infra: &infra
  labels:
    class: 'infra'
    cluster: 'pentest_lab'

networks:
  pentest_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

services:
  # Default attack system.
  kali:
    <<: *red_team
    build:
      context: ./
      dockerfile: dockerfiles/kali
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.5
    hostname: kali
    volumes:
      - kali-data:/root/Documents
  heimdall:
    <<: *infra
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=nope_uid
      - PGID=nope_gid
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.225
    hostname: heimdall
    ports:
      - 7000:80
    volumes:
      - ./etc/heimdall/config:/config
